[greeter]
theme-name = Adwaita-dark
icon-theme-name = Tela-circle-pink-dark
background = /usr/share/backgrounds/boykisser/boykisser1.png
user-background = false
font-name = Cantarell 11
xft-antialias = true
xft-hintstyle = hintslight
xft-rgba = rgb
indicators = ~host;~spacer;~clock;~spacer;~layout;~session;~power
clock-format = %A  %d %B   %H:%M
position = 50%,center 58%,center
